name: Build project

on: [push, pull_request]

jobs:
    buildForWebGL:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - WebGL
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                lfs: true
            
            - name: Caching unity project folders
              uses: actions/cache@v3
              with:
                path: ${{ vars.PROJECT_ROOT_PATH }}/Library
                key: ${{ vars.PROJECT_ROOT_PATH }}/Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                restore-keys: Library-
                    
            - name: Build unity project
              uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                projectPath: ${{ vars.PROJECT_ROOT_PATH }}
                targetPlatform: ${{ matrix.targetPlatform }}
            
            - name: Upload build to artifacts
              uses: actions/upload-artifact@v3
              with:
                name: Build-${{ matrix.targetPlatform }}
                path: build/${{ matrix.targetPlatform }}

            - name: Upload addressables to S3
              uses: shallwefootball/s3-upload-action@master
              id: S3
              with:
                  aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
                  endpoint: ${{ secrets.AWS_ENDPOINT }}
                  source_dir: ${{ vars.PROJECT_ROOT_PATH }}/ServerData/${{ matrix.targetPlatform }}
                  destination_dir: ${{ matrix.targetPlatform }}

            - name: Setup SSH keys
              run: |
                set -eu
                mkdir "$HOME/.ssh"
                echo "${{ secrets.SERVER_SSH }}" > "$HOME/.ssh/key"
                chmod 600 "$HOME/.ssh/key"

            - name: Copy WebGL build files to server
              run: |
                cd build/WebGL 
                rsync -azvhPL -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@${{ secrets.SERVER_IP }}:${{ vars.SERVER_PATH_TO_BUILD }}
