name: Build and deploy

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    buildAndDeploy:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - WebGL
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                lfs: true
            
            - name: Caching unity project folders
              uses: actions/cache@v4
              with:
                path: ${{ vars.PROJECT_ROOT_PATH }}/Library
                key: Library-${{ matrix.targetPlatform }}
                restore-keys: |
                    Library-${{ matrix.targetPlatform }}
                    Library-
                    
            - name: Build unity project
              uses: game-ci/unity-builder@v4
              id: build
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                projectPath: ${{ vars.PROJECT_ROOT_PATH }}
                targetPlatform: ${{ matrix.targetPlatform }}

            - name: Upload addressables to S3 and remove other files in S3 
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_S3_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
                  SOURCE_DIR: ${{ vars.PROJECT_ROOT_PATH }}/ServerData

            - name: Setup SSH keys
              run: |
                set -eu
                mkdir "$HOME/.ssh"
                echo "${{ secrets.SERVER_SSH }}" > "$HOME/.ssh/key"
                chmod 600 "$HOME/.ssh/key"

            - name: Upload WebGL build files to server
              run: |
                cd build/WebGL 
                rsync -azvhPL -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@${{ secrets.SERVER_IP }}:${{ vars.SERVER_PATH_TO_BUILD }}

            - name: Push updated version file back to repository
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: '[CI/CD] updated project to ${{ steps.build.outputs.buildVersion }} version'
                  commit_options: '--no-verify --signoff'
                  file_pattern: ${{ vars.PROJECT_ROOT_PATH }}/ProjectSettings/ProjectSettings.asset
                  #tagging_message: 'v${{ steps.build.outputs.buildVersion }}'
